### ISSUE TITLE
Python problem

### ISSUE THREAD

**Issue by forall** [izderadicka/xapi-back#1]
Hi,

I test your script but I have some problem with python2.6 and python2.7

- with python2.7 I have error: 
xb list
Traceback (most recent call last):
  File "/usr/bin/xb", line 2, in <module>
    import xapi_back.cli as cli
ImportError: No module named xapi_back.cli

CentOS 6.7 x64, python2.7
pip list
importlib (1.0.3)
importlib-full (0.0.1)
pip (7.1.2)
setuptools (18.1)

With python2.6 I have:
xb list
/usr/lib/python2.6/site-packages/argparse.py:1575: DeprecationWarning: The "version" argument to ArgumentParser is deprecated. Please use "add_argument(..., action='version', version="N", ...)" instead
  """instead""", DeprecationWarning)

**Comment by izderadicka** [comment]
Hi,

re: 2.6  -   not sure, why deprecation warning is there - I've tested 
only on 2.7, but if it is deprecation warning should not influence 
functionality
re: 2.7  - it seems like python path problem -   are you sure xapi-back 
is installed in python2.7  path?   If you installed with python 2.6 
it'll be in different path.

Regards

Ivan

**Comment by forall** [comment]
Hi,

With python2.6 it's work,  with 2.7 after a fresh install I have problem with SSL, it's missing some python package?

xb list
Error in command list: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/xapi_back/cli.py", line 207, in main
    cmd.execute()
  File "/usr/lib/python2.7/site-packages/xapi_back/cli.py", line 98, in execute
    with XAPISession(s['url'], s.get('user'), s.get('password')) as session:
  File "/usr/lib/python2.7/site-packages/xapi_back/cli.py", line 73, in __enter__
    self._password)
  File "/usr/lib/python2.7/site-packages/xapi_back/XenAPI.py", line 245, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/site-packages/xapi_back/XenAPI.py", line 140, in xenapi_request
    self._login(methodname, params)
  File "/usr/lib/python2.7/site-packages/xapi_back/XenAPI.py", line 164, in _login
    result = _parse_result(getattr(self, 'session.%s' % method)(*params))
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1308, in single_request
    self.send_content(h, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1456, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by izderadicka** [comment]
Hi,

check this:
https://www.python.org/dev/peps/pep-0476/

 From 2.7.9  python checks SSL certificates by default,  and it seems 
that root/server certificate is not available for python/openssl
there are two options:

a) Add root/server certificate to correct place, where python is looking 
for them (python is using openssl library I think)
b) Disable certificate check -

import ssl

# This restores the same behavior as before.
context = ssl._create_unverified_context()


This should add to code somewhere -   we might add it to xb client in 
future.


Regards
I.

**Comment by izderadicka** [comment]
Added argument --no-ssl-crt-check in latest commit 4251328b0ec90b3e12f0e2972ea7c381fb510f00 - pls check if it works with this argument

**Comment by forall** [comment]
With this argument it's works correct. 

[root@srvcamunda ~]# xb --no-ssl-crt-check list
Host    VM             State    AutoBck      AutoBck Batch  Last Backup         Dur. (m)
------  -------------  -------  ---------  ---------------  ----------------  ----------
xhost1  ad.test.local  Halted   false                       2015-09-02 14:49        11.6
xhost1  ps             Halted   false                       2015-09-02 12:10        25
