### ISSUE TITLE
VM moved, backup not reconized

### ISSUE THREAD

**Issue by guestisp** [izderadicka/xapi-back#15]
I've moved some VMs (already backuped) between XenServer hosts.
Now, doing a `xb list` these VMs are marked as without backup (I don't see any value in 'Last Backup` column)

How can I fix this ? I don't see any 'cache' file used by xapi-backup

**Comment by izderadicka** [comment]
The backup is stored in directory (root directory is set in conf file) 
named by VM name and UUID -  if you moved VMs, they will have probbaly 
different UUID.
Manual fix could be possible - just rename directory to match new UUID.

I.

**Comment by izderadicka** [comment]
Is my answer enough helpful to resolve your issue?

**Comment by guestisp** [comment]
Sorry for the delay. i've not tried yet, but I think you are right, i've totally forgot the UUID change after the migration.

**Comment by guestisp** [comment]
Yes, by changing the UUID i'm able to see the VM as properly backupped.

Any way to automate this? I've transfered about 90 VMs in last months, changing the UUID manually would be a pain.

**Comment by izderadicka** [comment]
Not now,
you can start new backups in new dir and then remove old dirs later ( 
you can for instance mass delete by mtime), in meanwhile if recovery is 
needed you can choose which backup to use with uuid argument ( if names 
are same).

I.

**Comment by guestisp** [comment]
I think the best way would create a script that connect to each host, dump a VMs list (with each UUID) and then rename locally

**Comment by mkaliyannan** [comment]
If you guys wish take a look at xen-orchestra source code. They developed under node based on Xenapi only. It's under github only. It will help you lot to add features

**Comment by izderadicka** [comment]
in order to recognize that VM has been moved xb will need additional information. Either this can be part of required move functionality in issue #14 or new commad merge command is needed

**Comment by izderadicka** [comment]
Today have done similar task and see the problem. I think right solution would be to have option to rename local store directory with new vm uuid if required

**Comment by guestisp** [comment]
Still having issue restoring VMs:

```
# l -d /var/backups/xenserver/xxx#*
drwxr-xr-x 2 root root 2 Oct 10  2016 /var/backups/xenserver/xxx#581e8e65-e934-5380-0b16-c8b1d8c2e139
drwxr-xr-x 2 root root 4 Jul 14 08:28 /var/backups/xenserver/xxx#652963c5-59d4-c584-7a87-cc38c4661f4f

# xb restore --host my.server --uuid 652963c5-59d4-c584-7a87-cc38c4661f4f --vm xxx --insecure 
Error in command restore: No backup to restore for VM xxx
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/cli.py", line 323, in main
    cmd.execute()
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/cli.py", line 134, in execute
    self.execute_for_one(session, s)
  File "/usr/local/lib/python2.7/dist-packages/xapi_back/commands/restore_one.py", line 38, in execute_for_one
    raise CommandError('No backup to restore for VM %s' % vm_name)
CommandError: No backup to restore for VM xxx
```

Even doing a `xe list` the backup is not shown in the list.
Any idea ? I have to fix this ASAP

**Comment by izderadicka** [comment]
all information about backup is just stored in directory - in main directory (specified in config) there is a directory for each backed up VM,   this directory name is in form vm_name#uuid. The directory contain backup files (*.xva.gz - if ungzipped you can also use other xen tools to restore) and *.xva.gz.size which contains some metadata for related backup file).
In you case it should be enough to rename directory xxx#581e... (assuming it contains some files)   to xxx#65293...  (if later does not contain any files) or copy latest couple of files from  xxx#581e...   to xxx#65293... .

**Comment by guestisp** [comment]
But why i have to rename the old backup over the new one ?
The backup I have to restore is in xxx#652963c5-59d4-c584-7a87-cc38c4661f4f properly stored in the backup directory, as shown above

**Comment by izderadicka** [comment]
And does it have some files in it?

**Comment by guestisp** [comment]
Sure!

**Comment by izderadicka** [comment]
can you share list ls -laR xxx#* - e.g to see files in dirs?  If there are correct files some backups should be there. The only other possibility is if compression method has changed -  e.g.  if all backup files are gzipped, but later configuration changed not to use compression then these files will not be visible.

**Comment by guestisp** [comment]
```
# ls -laR xxx#652963c5-59d4-c584-7a87-cc38c4661f4f/
xxx#652963c5-59d4-c584-7a87-cc38c4661f4f/:
total 91160358
drwxr-xr-x  2 root root           4 Jul 14 08:28 .
drwxr-xr-x 81 root root          87 Sep 24  2017 ..
-rw-r--r--  1 root root 93307758456 Jan 26  2017 20170126_101339_2d5b_.xva.gz
-rw-r--r--  1 root root          26 Jan 26  2017 20170126_101339_2d5b_.xva.gz.size
```

maybe it's because i have compress set to false in config file and this is a very old backup, where compression was still active.

**Comment by izderadicka** [comment]
> maybe it's because i have compress set to false in config file

Exactly - easiest solution would be to set compress to true temporarily or have alternative config with that and use --config argument

Or manually you can ungzip backup and rename .xva.gz.size to .xva.size
